### ISSUE TITLE
YUILibrary.com HTTPS certificate expired and yogi is failing

### ISSUE THREAD

**Issue by henvic** [yui/yogi#101]
`yogi serve` is failing.

Investigating I discovered that this is because, for some reason, at start-up yogi tries to connect to [yuilibrary.com via HTTPS](https://yuilibrary.com/), and the domain's HTTPS certificate expired some days ago.

When not connected to the Internet:
`
$ yogi serve
yogi [info]  using yogi@0.1.12 on node@0.11.13
yogi [info]  using aui-ace-editor, aui-affix, aui-aria, aui-alert, aui-arraysort, aui-audio, aui-base, aui-autosize, aui-button, aui-carousel, aui-char-counter, aui-classnamemanager, aui-color-picker, aui-collection, aui-css, aui-component, aui-datepicker, aui-datatable, aui-datatype, aui-debounce, aui-diagram-builder, aui-dropdown, aui-event, aui-form-validator, aui-form-builder, aui-image-cropper, aui-io, aui-image-viewer, aui-messaging, aui-modal, aui-node, aui-pagination, aui-palette, aui-parse-content, aui-popover, aui-progressbar, aui-promise, aui-property-builder, aui-rating, aui-scheduler, aui-scrollspy, aui-search, aui-selector, aui-sortable, aui-surface, aui-tabview, aui-text-unicode, aui-timepicker, aui-timer, aui-toggler, aui-toolbar, aui-tooltip, aui-tree, aui-undo-redo, aui-url, aui-video, aui-viewport, aui-widget, anim, app, async-queue, arraysort, attribute, base, autocomplete, button, cache, calendar, charts, classnamemanager, collection, color, console, console-filters, cssbase, cssfonts, cookie, cssgrids, cssnormalize, dataschema, cssreset, datasource, datatable, dial, date, dd, dom, dump, editor, escape, event-custom, event, event-gestures, event-simulate, event-valuechange, file, gesture-simulate, graphics, get, history, handlebars, highlight, imageloader, intl, json, io, jsonp, loader, matrix, node-flick, node, node-focusmanager, node-scroll-info, node-menunav, oop, number, overlay, panel, paginator, parallel, plugin, pjax, promise, pluginhost, recordset, queue-promote, querystring, resize, scrollview, sortable, slider, substitute, stylesheet, swf, tabview, swfdetect, template, test, test-console, transition, text, timers, tree, uploader, widget, widget-anim, widget-autohide, widget-buttons, widget-child, widget-modality, widget-parent, widget-position-align, widget-position-constrain, widget-position, widget-stack, widget-stdmod, xml, yui-throttle, yql, yui, foo, something, in, module-1, module-2, csswithassets, calendar, cssreset, event, uploader, yql2, yql, mymodule, myothermodule, in, module-1, module-2, calendar, cssreset, csswithassets, event, uploader, yql, yql2
yogi [info]  adding tests route
yogi [info]  launching xdr server on port 5003
yogi [bail] { [Error: getaddrinfo ENOTFOUND]
  stack: 'Error: getaddrinfo ENOTFOUND\n    at errnoException (dns.js:41:10)\n    at Object.onlookup [as oncomplete] (dns.js:91:26)',
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'yuilibrary.com' }
`

When connected to the Internet:
`
$ yogi serve
yogi [info]  using yogi@0.1.12 on node@0.11.13
yogi [info]  using aui-ace-editor, aui-affix, aui-alert, aui-arraysort, aui-aria, aui-audio, aui-autosize, aui-base, aui-button, aui-carousel, aui-char-counter, aui-classnamemanager, aui-collection, aui-color-picker, aui-component, aui-css, aui-datatable, aui-datatype, aui-datepicker, aui-debounce, aui-diagram-builder, aui-dropdown, aui-event, aui-form-builder, aui-form-validator, aui-image-cropper, aui-image-viewer, aui-io, aui-messaging, aui-modal, aui-node, aui-pagination, aui-popover, aui-palette, aui-parse-content, aui-progressbar, aui-promise, aui-property-builder, aui-scrollspy, aui-search, aui-scheduler, aui-rating, aui-selector, aui-sortable, aui-surface, aui-tabview, aui-text-unicode, aui-timepicker, aui-toggler, aui-timer, aui-tooltip, aui-toolbar, aui-tree, aui-undo-redo, aui-url, aui-video, aui-viewport, aui-widget, anim, app, async-queue, arraysort, attribute, autocomplete, button, base, cache, calendar, charts, classnamemanager, collection, color, console, console-filters, cookie, cssbase, cssfonts, cssgrids, dataschema, cssreset, cssnormalize, datatable, datasource, dial, date, dd, dom, dump, editor, event, escape, event-custom, event-simulate, event-gestures, event-valuechange, gesture-simulate, file, get, graphics, handlebars, highlight, intl, history, imageloader, io, jsonp, json, loader, matrix, node, node-flick, node-focusmanager, node-scroll-info, node-menunav, overlay, number, oop, paginator, panel, parallel, plugin, pjax, pluginhost, querystring, recordset, promise, queue-promote, scrollview, slider, resize, stylesheet, sortable, substitute, tabview, swfdetect, swf, template, test, test-console, timers, text, uploader, transition, tree, widget, widget-anim, widget-autohide, widget-child, widget-buttons, widget-modality, widget-parent, widget-position, widget-position-align, widget-position-constrain, yui, widget-stack, widget-stdmod, xml, yql, yui-throttle, foo, something, in, module-1, module-2, calendar, cssreset, csswithassets, event, uploader, yql, yql2, mymodule, myothermodule, in, module-1, module-2, calendar, cssreset, csswithassets, event, uploader, yql, yql2
yogi [info]  adding tests route
yogi [info]  launching xdr server on port 5003
yogi [bail] { [Error: certificate has expired]
  stack: 'Error: certificate has expired\n    at Error (native)\n    at TLSSocket.<anonymous> (_tls_wrap.js:906:36)\n    at TLSSocket.EventEmitter.emit (events.js:104:17)\n    at TLSSocket._finishInit (_tls_wrap.js:457:8)',
  code: 'CERT_HAS_EXPIRED' }
`

PS: I'm going to take a look next week if this isn't fixed yet.

**Comment by caridy** [comment]
@henvic I did a quick patch to solve this issue. We are not renewing the SSL certification on yuilibrary.com, instead, yogi now uses `http`.
- yogi@0.1.13
