### ISSUE TITLE
Sellect paths for examples of gallery modules

### ISSUE THREAD

**Issue by Satyam** [yui/yogi#11]
When using `yogi serve --instanbul` I find I cannot run the examples because the wrapper it puts around the generated page loads the YUI seed file from `../../build/` which is correct for YUI core modules but not for gallery ones.

There seems to be a `yuiSeedUrl`placeholder to change this but setting this in a `project.json` file or `component.json` file in the module being served by yogi made no difference.

I wouldn't like to have this path fixed to any version, as it normally happens with yui seed files, it would be good if the gallery developer would be able to run the examples and tests against whatever the latest version of YUI without having to edit anything.  Perhaps, an option to run the examples with pre-releases, but that should be an option.

On the other hand, it would be great to have an equivalent feature for our own modules, that is, load the gallery modules from the `../../build` directory since that would allow me to do changes and test them at the same time.  Normally it loads them from the CDN  if I don't explicitly use a `YUI({ ... cfg ...}).use()`  but that would not work when up in the CDN nor would it look good in the docs because it would lend the reader to think it is something the developer must write.

Perhaps the best solution is to have the template load a file with the `YUI_config` variable with the module definitions (generated by yogi loader?  perhaps it does this, but I couldn't make it work, but that is another issue) so that I can set up such a file in my local environment while, once in the CDN,  that would be ignored.

**Comment by davglass** [comment]
Either put the yui3 repo one step up from your gallery or `yogi config
set yui /path/to/yui/git/repo`

That should serve them.

**Comment by Satyam** [comment]
You should be on vacation!  Go away! :)

Anyway, it didn't work, I have:

```
satyam@ubuntu:~/git/myGallery/src/gallery-fwt-treeview$ yogi config get yui
yogi [info]  using yogi@0.0.44 on node@0.8.14
yogi [info]  yui is currently set to:
http://yui.yahooapis.com/3.7.3/build/yui/yui-min.js
```

but the examples still try to load them from the same place.

Anyway, I think this is something that should be configured locally since some developers might be working at the YUI Core and at his/her own Gallery modules and changing it back and forth would be troublesome.  And, the second part, about where to load the gallery modules (at least those that belong to the developer) remains.

**Comment by davglass** [comment]
Not a URL a path to the source on disk.

**Comment by Satyam** [comment]
Amazing!
It also pulls the local copy of my gallery modules and from the CDN for others!  
Thanks
