### ISSUE TITLE
yogi init (and other commands?) should not require login

### ISSUE THREAD

**Issue by evangoer** [yui/yogi#12]
The init functionality is awesome, but -- it seems odd to have to log in to the Gallery or to GitHub just to generate a project skeleton. I might not care about the Gallery, this might be an entirely internal project where I might be using bzr or something crazy, etc.

I haven't checked out other yogi commands extensively, but perhaps do a sweep through all the commands in order to figure out which ones really do need to be coupled with GitHub and the Gallery.

**Comment by davglass** [comment]
Yup, they shouldn't need one. I'll get this patched ASAP.

**Comment by davglass** [comment]
Pushed in `yogi@0.0.45`
