### ISSUE TITLE
Make yogi init a standalone command line tool

### ISSUE THREAD

**Issue by evangoer** [yui/yogi#13]
## Minimum

Break out the 'init' functionality into a separate npm tool, so that if you only care about generating project skeletons, you can do that and ignore the rest.
## Hopes & dreams

Make it very easy to augment this tool with new templates. Ideally as simple as, make an npm package that provides a project directory structure + some files with handlebars markup. If you add that npm package, our fancy init tool discovers it and registers it as yet another option.

Grunt kind of has this ability to add more project skeletons, but it's clunky and more tightly coupled than I'd like.

**Comment by evocateur** [comment]
I really like this idea. So much so, that I may even carve out time to hack a little toward it...

**Comment by davglass** [comment]
I'm not a "huge" fan of this approach unless its done very very well.
I'm pushing for those creating modules to also benefit from the other
yogi commands like lint & test. Breaking only the init out seems too
light for the added complexity.

I do however want to support sub commands similar to git (e.g.
yogi-init, yogi-test, yogi-foo) & this might be a good one to try, but
I fear fragmenting the shared code base might be confusing to users &
harder to maintain for the maintainer (me).

**Comment by evocateur** [comment]
Totally fair. I guess I'm really looking for a configurable template (although really, the current default is really sweet). Maybe I'll experiment with more customization options for the existing init template.

yogi subcommands would be great. Something like `yogi-lessc` would be dreamy for those of us trying to move toward CSS preprocessors in a sane way.

**Comment by evangoer** [comment]
Alright, leaving aside the idea of breaking init out as a standalone tool -- what do you think of having a standard, easy way to add and modify init templates? 

I don't have this fully worked out in my head, but I feel like init templates should look something like this:
1. define a directory structure, with filepaths that can take placeholders
2. define files within that file structure, with contents that can take placeholders
3. package up this directory structure and register it with yogi in some easy way

The current default functionality is great, but generating project skeletons is definitely something people will want to hack on. And a skeleton that's good for me at Yahoo! might not be good for someone working at Zillow, and vice versa. :)

**Comment by davglass** [comment]
Yes, I think a way to have customized templates would be a good thing. I'll think on this a bit to see what I can some up with..

**Comment by davglass** [comment]
FYI, I added in support for executing custom `yogi-foo` executables as `yogi foo`

https://github.com/davglass/yogi-foo

**Comment by evangoer** [comment]
Perfect!
