### ISSUE TITLE
yogi calls me 'undefined'

### ISSUE THREAD

**Issue by Satyam** [yui/yogi#17]
After successfully login in both to the YUI library and GitHub, a yogi info shows 'undefined' where my username should be, like in:

```
repo:       git://github.com/undefined/yui3-gallery.git
```

I've been called a lot of things in my life, but this is a first.

My guess is that this is what is preventing me from switching to the repo which returns with a:

```
yogi [bail] Not Allowed
```

yogi whoami identifies me correctly.

Thanks

**Comment by davglass** [comment]
Can you email me the filtered content of ~/.yogi.json (minus the tokens)

**Comment by Satyam** [comment]
```
{
    "apiHost": "yuilibrary.com",
    "gh_token_date": "2012-11-22T17:53:02Z",
    "yui": "/home/satyam/git/yui3-1",
    "username": "Satyam",
    "token": "intentionally left blank",
    "gh_user": "Satyam",
    "gh_token": " intentionally left blank"
}
```

**Comment by davglass** [comment]
This should work now, can you give it a shot?

**Comment by Satyam** [comment]
Getting close, but not there yet.  yogi info now identifies me correctly, however yogi info --set-repo still returned with:

```
satyam@ubuntu:~/git/myGallery/src/gallery-fwt-treeview$ yogi info --set-repo=yui3-new-gallery
yogi [info]  using yogi@0.0.45 on node@0.8.14
yogi [info]  using module: gallery-fwt-treeview
yogi [info]  updating info for this module:
yogi [info]  setting repo to: yui3-new-gallery
yogi [bail] Not Allowed
```

**Comment by davglass** [comment]
Can you please try it now?

**Comment by Satyam** [comment]
Works, I think.

The `--set-repo` worked fine.  The `--set-path` works, but I'm not sure I understand it.  

My repository is in:  `https://github.com/Satyam/yui3-new-gallery`.   My local working copy is in `~/git/myGallery`.   I assume the `--set-path`  is the folder, relative to wherever I have my working copy, of the particular module I'm setting.  

Thus, for gallery-fwt-treeview, which is at `~/git/myGallery/src/gallery-fwt-treeview` it is simply: `--set-path=/src/gallery-fwt-treeview`.  However, `yogi info` reports it as `cd yui3-new-gallery/src/gallery-fwt-treeview`.  

Is that correct?

Thanks

**Comment by davglass** [comment]
The repo is the name of the repo on github, so in this case it would be `yui3-new-gallery`.

Your local path doesn't really matter, `yogi` is telling you the steps to clone that repo and what it will use to clone the repo and build the module for CDN deployment.

So, in other words `--set-path=/src/gallery-fwt-treeview` will report `cd yui3-new-gallery/src/gallery-fwt-treeview` since that's how the CDN build will locate your module.

**Comment by Satyam** [comment]
Then, I guess, I'm ready to go.  

Thanks, yogi is great!

**Comment by davglass** [comment]
:thumbsup:

**Comment by davglass** [comment]
My apologies, it's a common "rock and roll" icon. I'll remove it and not use it again. Hopefully that's better.
