### ISSUE TITLE
Allow for generation of rollups

### ISSUE THREAD

**Issue by kapilt** [yui/yogi#18]
For several applications combo loading isn't ideal. For such cases it would be great if yogi could generate a rollup of yui and the app files. At the moment its a pretty one off task for each project to setup the loader to generate a dep set and then minify/aggregate the result.

**Comment by davglass** [comment]
`yogi loader` is the starting point for this, more to come when `grifter` is released (very soon)

**Comment by evocateur** [comment]
Any news on the `grifter` front? I'd be willing to subject myself to alpha testing!

**Comment by davglass** [comment]
Last week I was pretty sick so I didn't get to work on it much. Yesterday I wrapped up the last module to make the gallery build work and have been testing it with the 20 modules in this weeks queue. Once I get a solid stable build from it I can add tests and commit it.. So it shouldn't be too long ;)

**Comment by evocateur** [comment]
Awesome, thanks!

**Comment by davglass** [comment]
Closing since this is not a yogi issue.
