### ISSUE TITLE
What's the url for an image in the docs/assets?

### ISSUE THREAD

**Issue by Satyam** [yui/yogi#19]
From the selleck guide it says the assets directory is for static resources.  In my case, I wanted to use an icon, like this:

```
<style>
    .www-go {
        width: 16px;
        height: 16px;
        background-image: url(assets/world_go.png);
}
</style>
```

The url is correct relative to the page of the `.mustache` page containing that style declaration, the image is there and it has the right permissions.  However, yogi translates those addresses and I don't know how to tell it to handle this one. The network tab shows it in red with a 404 message.  

I tried several combinations to try to beat the routing, but couldn't find the way and, anyway, I'm not sure any tricks I could do locally  would work once up in the CDN.

Thanks for the help

**Comment by davglass** [comment]
Use the mustache variable `{{componentAssets}}` like this:

``` html
<style>
    .www-go {
        width: 16px;
        height: 16px;
        background-image: url({{componentAssets}}/world_go.png);
   }
</style>
```

That should work.

**Comment by Satyam** [comment]
It does, thanks again.
