### ISSUE TITLE
yogi info reports no tests

### ISSUE THREAD

**Issue by Satyam** [yui/yogi#20]
At the bottom of the `yogi info` screen, it says:

```
yogi [warn]  this module does not provide tests
```

What is it that it checks to say so, because I have an index.html file in tests/unit and that runs a .js file a further level down, in fact, I got 'green'  status in coverage with the tests.

Perhaps it is checking what's up in the new gallery which, at this point is nothing?  If so, that will change, hopefully in the next build.

Thanks

**Comment by davglass** [comment]
Those are the reported tests from a CDN deployment. Right now it contains no tests in the remote system because it hasn't been built yet. Maybe I should change the wording there?

**Comment by Satyam** [comment]
Perhaps the report could be broken into local and remote sections.  The lack of tests goes into the remote part.  

Remember I asked about what the --set-path meant?  It was the path on the remote part, that is, from the root of the github project.  Remote stuff.

Perhaps breaking the options into local and remote might help and perhaps make it possible to report tests and/or test results at both ends. (by storing the results of the tests somewhere locally perhaps?)

Anyway, this is definitely a temporary issue.  Right now, it is confusing because it is the first time and I'm trying to get things right.  On the other hand, later on, you wouldn't need yogi info to tell you this.

**Comment by davglass** [comment]
This will be in `yogi@0.0.47`
