### ISSUE TITLE
shortpath config not honored in file names

### ISSUE THREAD

**Issue by kara-ryli** [yui/yogi#22]
You cannot create non-YUI core modules without the `gallery-` prefix.

```
$ yogi config set shortpath true
$ yogi init test-module
...
yogi [info]  module created, here's what yogi did for you:

   src/test-module
       ├── HISTORY.md
       ├── README.md
       ├── assets/
       ├── build.json
       ├── css/
       ├── docs/
       │  ├── component.json
       │  └── index.mustache
       ├── js/
       │  └── gallery-test-module.js
       ├── meta/
       │  └── gallery-test-module.json
       └── tests/
          └── unit/
             ├── index.html
             └── js/
                └── tests.js
```

This is caused by createDirs in `lib/create.js` using this check to determine the prefix: `options.name.indexOf('gallery') === -1 && !util.isYUI()`.

**Expected behavior**: generated files should be named `test-module.js`, etc. Perhaps that's by design, but it would be great if this were possible.

**Workaround**: create a `package.json` file in your source root like this:

```
{
  "name": "yui"
}
```

Although I'm guessing that would break other things.

**Comment by davglass** [comment]
This will be in `yogi@0.0.47`
