### ISSUE TITLE
Define charset for unit tests

### ISSUE THREAD

**Issue by solmsted** [yui/yogi#24]
I noticed when I run unit tests from yogi serve, Firebug throws errors because there is no character set defined in either a response header or a meta tag.  I just ignored that error until I wrote some tests and they were failing and I couldn't figure out why.  The solution was to add `<meta charset="utf-8" />` in the `<head>` of index.html.

Is utf-8 a reasonable default character set?  If so, could it be added to Yogi's template?

**Comment by davglass** [comment]
Yup, all things should be utf-8. I can add the meta to the template
file & I can look at having the server auto add the utf-8 content type
to all text based requests.

**Comment by davglass** [comment]
This will be in `yogi@0.0.47` in a bit.
