### ISSUE TITLE
Partials and properties supported

### ISSUE THREAD

**Issue by Satyam** [yui/yogi#28]
I've just watched Apipkin's talk and learned of a couple of predefined partials, properties or whatever.  From you I learned about the {{componentAssets}}.   Is there a list somewhere with all of them?

BTW, I tried the {{>getting-started}}  and it produces this:

```
<script>
// Create a new YUI instance and populate it with the required modules.
YUI().use(, function (Y) {
    // Gallery: gallery-flyweight-tree is available and ready for use. Add implementation
    // code here.
});
</script>
```

with the module name missing in the YUI().use().  Am I missing something?  The name property is there in all the .json files where it can possibly be.

**Comment by davglass** [comment]
Check out the Selleck docs, that is what is serving these docs under the hood: http://yui.github.com/selleck/

_I'll look into the name thing, that's probably a yogi config issue_

**Comment by davglass** [comment]
Add this to your `docs/component.json` file:

```
"use": [ "gallery-flyweight-tree" ]
```

**Comment by Satyam** [comment]
Apipkin's example doesn't show any "use" property.  It works once you know.

The selleck docs don't list any of those partials or properties.  It barely mentions there can be an assets folder, but how to handle it, it doesn't say.  No getting-started or much of anything else.

**Comment by davglass** [comment]
I just took over Selleck from @rgrove and I haven't had a chance to "beef up" the docs yet. I'll ping @evangoer to see if he can spin me some docs for it :)

**Comment by Satyam** [comment]
I know, and I'm not complaining, but I had to post it for the record.  Should I better post it on Selleck?

**Comment by davglass** [comment]
Sure, file an issue there so that I have a record of it in the project that needs docs ;)

**Comment by rgrove** [comment]
Part of the reason for this is that many of these conventions are YUI-specific, and don't belong in Selleck's generic docs. We had a page somewhere that documented many of these YUI-specific conventions, but I can't remember where that was. I think it may have been internal?

**Comment by evangoer** [comment]
Is Selleck a tool for constructing YUI user guide pages, or a generic documentation tool? If it's the former, there should be one master page describing all of the partials and properties, including YUI-specific ones. If it's the latter, then there's a case for splitting out project-specific conventions into their own list.

**Comment by rgrove** [comment]
Initially I wanted it to be the latter. Turns out I didn't care enough to make it a generic documentation tool, so it should probably just be the former.

**Comment by davglass** [comment]
That was my point, it's more of a YUI tool that others "can use".
