### ISSUE TITLE
yogi update didn't save meta "requires" data from build.properties

### ISSUE THREAD

**Issue by stlsmiths** [yui/yogi#29]
I did a "yogi update" in a new directory for one of my gallery components, and in the meta/ path the 
.json file didn't convert any of the "requires" ... so my gallery is dead for this week.

For example: https://github.com/stlsmiths/new-gallery/tree/master/src/gallery-datatable-paginator

Probably happened because I don't know what the hell I am doing yet with yogi.  

But as a test, I copied Dav's bitly project from his link:  https://github.com/davglass/gallery/tree/master/src/bitly

Then I deleted the build.json, css, docs, meta and tests folders ... leaving just the assets, js and build.properties and build.xml files.

I then did "yogi update", it proceeded to do the conversion.  But when I checked the meta/bitly.json file it contained just "{  "bitly":{} }" and didn't copy the "base,get" requires.

yogi version 0.0.46.

I'll go ahead and manually edit the meta .json file, but wanted to pass this on FWIW.

**Comment by davglass** [comment]
Sorry for that, I'll get this patched ASAP. If you want, please file another CDN request and I'll do another build tomorrow with the fix :)

**Comment by davglass** [comment]
I've pushed a quick patch, can you install from master to see if this works for you now?

`npm -g install https://github.com/yui/yogi/archive/master.tar.gz`

**Comment by stlsmiths** [comment]
Thanks Dav, I tried the fix above (yogi v 0.0.48) and it worked.  Looks like it put the requires stuff in the build.json file.

I won't update my gallery stuff til next week, I have tests and other stuff to repair from this week's pushes.

**Comment by davglass** [comment]
I just pushed another patch, the `config` on the build.json should be removed and added to the `meta` file. It should work that way now.

**Comment by davglass** [comment]
If you need another gallery build before next week just let me know. I can run one at any time to test out grifter ;)

**Comment by stlsmiths** [comment]
So for sake of argument, if bitly had skinnable=true, is this correct for build.json ?

```
{
    "name": "bitly",
    "builds": {
        "gallery-bitly": {
            "config": {
                "skinnable": "true",
                "requires": [
                    "base",
                    "get"
                ]
            },
            "skinnable": "true",
            "jsfiles": [
                "bitly.js"
            ],
            "meta": {}
        }
    }
}
```

which is what 0.0.48 just created

There aren't any code examples of build.json on the shifter or yogi docs pages

**Comment by davglass** [comment]
There are tons of docs about the `build.json` file here: http://yui.github.com/shifter/#build.json.

To your question, yes it will work but it is not recommended. All of the module meta-data should live in the meta/*.json file. That way Loader can parse and build it's internal meta-data store from it. Loader will not parse the build.json file, so if it's not in the meta file the Loader meta will not work.

As for my latest push, it should remove the `config` key from the build.json file and add that to the `meta/*.json` file.
