### ISSUE TITLE
Links in coverage report

### ISSUE THREAD

**Issue by Satyam** [yui/yogi#31]
This is absolutely low priority, but it would be nice.

If you run the tests with coverage and you click on the back button of the browser, you don't go to the root of the yogi server but to the test, which sends you back to the coverage report.

Also, I'm looking at the detailed coverage report of one file, the one that shows the source and which branches were taken, which statements executed and so on.  When I add a test, it is kind of boring to refresh that result.

It would also be great if the report went straight to the first warning and provided means to jump from one warning to the next.

**Comment by davglass** [comment]
I'll look into this. The reporting is handled by Istanbul and I just redirect you there. I need a general way to add a Yogi header to the top of all the sub pages for navigation purposes like this.
