### ISSUE TITLE
Why yogi serve works with yui core but not with my modules?

### ISSUE THREAD

**Issue by Satyam** [yui/yogi#33]
If I cd into the Core repository and launch yogi serve, it works, but if I do the same on my group of gallery modules, all in the same repository, it asks for the module.  It doesn't do that with the core.  What should I have in my gallery repository to make that work?

I can see the API docs for the whole core (and I would like to see that for a couple of my modules, since one of them inherits from another one) and full examples and landing pages.

I guess I need some sort of index.  There are a couple of files there that seem to provide that, but I'm not sure what they really are.

Thanks

**Comment by davglass** [comment]
That's a bug that I'm working on. It works on the module level in the gallery, but not all of them.. I'll take a look at this soon.

**Comment by davglass** [comment]
You can install this from master to test this before the next release:

`npm -g install https://github.com/yui/yogi/archive/master.tar.gz`

**Comment by Satyam** [comment]
API docs, tests and coverage work fine, User Guides makes it crash. API 
docs now look great because references from a subclass to its superclass 
work nicely so now you can see the whole set of members, its own and 
those inherited.

Satyam

**Comment by davglass** [comment]
How does it crash? Can you paste the error output? Mine serves properly.

**Comment by Satyam** [comment]
satyam@ubuntu:~/git/myGallery/src$ yogi serve
yogi [info]  using yogi@0.0.51 on node@0.8.15
yogi [info]  using gallery-flyweight-tree, gallery-timeline, 
gallery-button-plugin, gallery-md-ibutton, gallery-md-accordion, 
gallery-md-button, gallery-fwt-treeview, gallery-stdmod, 
gallery-md-timespinner, gallery-md-spinner, gallery-md-button-group, 
gallery-md-fieldgroup, gallery-md-model, gallery-makenode, 
gallery-md-inputfield
yogi [info]  adding tests route
yogi [info]  launching yuidoc --server 5003 --config 
/usr/lib/node_modules/yogi/configs/yuidoc/yuidoc.json
yogi [info]  launching selleck --server 5004 --project 
/usr/lib/node_modules/yogi/configs/selleck
yogi [info]  listening on: http://127.0.0.1:5000

stream.js:81
       throw er; // Unhandled stream error in pipe.
             ^
Error: connect ECONNREFUSED
     at errnoException (net.js:769:11)
     at Object.afterConnect [as oncomplete](net.js:760:19)
satyam@ubuntu:~/git/myGallery/src$

**Comment by davglass** [comment]
Make sure you don't have any other "stray" node servers sitting around (from a previous crash) `ps ax | grep node`. It looks like you might have some, since the ports should be `5000`, `5001` & `5002` not `5000`, `5003` & `5004`.

**Comment by davglass** [comment]
Also, is this on your repo? Can you point me to it so I can clone it to test with..

**Comment by Satyam** [comment]
https://github.com/Satyam/yui3-new-gallery

**Comment by Satyam** [comment]
I killed all the left over processes and run it again, with the same 
result.  Anyway, the very first time I run it, the user guide link was 
the first I tried, and that was the first time I had run yogi today, so 
it was fresh.  The left-overs were after that crash, they weren't from 
earlier versions.

**Comment by davglass** [comment]
Parse error in: `src/gallery-md-button-group/docs/component.json`

Using `yogi serve --debug` would show this. 

I'm adding an error output handler to the Selleck server under the hood to display errors like this in the future.

**Comment by davglass** [comment]
This is in `yogi@0.0.52`.

**Comment by Satyam** [comment]
Actually, now that I see the error, I guess that you don't need to 
bother.  This error was due to the yogi update process that didn't strip 
out the newlines from the description field received from the current 
gallery.  With that taken care of, this error shouldn't happen at all.

**Comment by davglass** [comment]
It "could" still happen if people hand write their own `component.json` files, so I left it in to throw the error to `stdout` so they can see their issue.
