### ISSUE TITLE
Add support for GitHub organizations

### ISSUE THREAD

**Issue by rgrove** [yui/yogi#34]
Yogi currently assumes that the git origin for a gallery module will always be relative to the configured GitHub user. For example, my GitHub username is "rgrove", so yogi assumes all my projects will live in repos under `github.com/rgrove`.

Unfortunately, this means yogi can't support GitHub organizations like `github.com/smugmug`, so organizations can't own gallery modules.

**Comment by davglass** [comment]
As of `yogi@0.0.61` you should be able to use `yogi info <module> --set-github=<github user/org>` and it will change it.

**Comment by davglass** [comment]
It should also "guess" the github user from the `origin` when you create a new one too.

**Comment by rgrove** [comment]
Yay!
