### ISSUE TITLE
Expose echoecho server on another port for XDR testing.

### ISSUE THREAD

**Issue by ericf** [yui/yogi#36]
Echoecho makes it easy to test `Y.IO` for standard XHRs, but in order to support testing cross domain requests, an echoecho server must be setup on a different origin.

Can we expose another echoecho server on a different port than the one yogi serves unit tests from, and expose where it's mounted? This way the `Y.IO` tests could properly test XDR transports.

**Comment by davglass** [comment]
I have a version of this checked in, you can install it with:

`npm -g install https://github.com/yui/yogi/archive/xdr.tar.gz`

To use it, there will be a `YOGI_CONFIG` global that you can key off of with a property called `xdrPort` that will contain the xdr port server to use.

**Comment by ericf** [comment]
Awesome! I'll give it a try today, and let you know how I end up.

**Comment by davglass** [comment]
Merged `xdr` in and published `yogi@0.0.56`.
