### ISSUE TITLE
Getting yogi [bail] today on module updated last week

### ISSUE THREAD

**Issue by stlsmiths** [yui/yogi#37]
My updated module "gallery-datatable-selection" was updated on the CDN push last week.

I made an update and this week tried to do a "yogi info" in the src/gallery-datatable-selection directory and get

```
yogi [info]  using yogi@0.0.53 on node@0.8.11
yogi [info]  using module: gallery-datatable-selection
yogi [info]  showing info for gallery-datatable-selection
yogi [bail] nothing known about gallery-datatable-selection
```

So I deleted the build.json file, did a yogi update, and it creates everything fine.  When I do another "yogi info" it gives the same "nothing known about gallery-datatable-selection" msg again.

Did I munge something up somehow?

using yogi 0.0.53

... actually, all of my gallery modules from last week, on `yogi info` come up this way

**Comment by davglass** [comment]
They should display again. Sorry for this issue, seems the JSON data for the test results/coverage was corrupted and a `JSON.parse` on the stored information was not working. I've fixed the issue with the failure, now I'm working on making sure the logs are transmitted properly.
