### ISSUE TITLE
`yogi build` on windows

### ISSUE THREAD

**Issue by jenny** [yui/yogi#39]
FYI: I'm on Win7 using Git Bash (sorry!)

`yogi build` does not work for me but `shifter` does:

jennyhan@GREENOURHEAT-L7 ~/web/git/yui3/src/uploader (uploader-examples)
$ yogi build
yogi [info]  using yogi@0.0.56 on node@0.8.16
yogi [info]  using module: uploader
yogi [info]  running with shifter
'c:\Users\jennyhan\AppData\Roaming\npm\node_modules\yogi\node_modules\shifter\bi
n\shifter' is not recognized as an internal or external command, operable program or batch file.
yogi [info]  build complete
yogi [ERROR] yogi detected an error, exiting code 1

jennyhan@GREENOURHEAT-L7 ~/web/git/yui3/src/uploader (uploader-examples)
$ shifter
shifter [info] racing to find the closest .shifter.json file
shifter [info] revving up
shifter [info] looking for build.json file
shifter [info] found build.json file, shifting
shifter [info] putting the hammer down, let's build this thing!
shifter [info] munging in loader meta data into build.json
shifter [info] munging in loader meta data into build.json
shifter [info] munging in loader meta data into build.json
shifter [info] munging in loader meta data into build.json
shifter [info] putting the hammer down
shifter [info] shifting into gear for uploader
shifter [info] shifting a copy
shifter [info] shifting into gear for uploader-queue
shifter [info] shifting into gear for uploader-html5
shifter [info] shifting into gear for uploader-flash
shifter [info] copying from c:\Users\jennyhan\web\git\yui3\src\uploader\swf\flashuploader.swf to c:\Users\jennyhan\web\git\yui3\build\uploader\assets\flashuploader.swf
shifter [info] down shifting the copy
shifter [queu] file has changed, continuing build
shifter [queu] writing RAW file
shifter [queu] writing RAW file
shifter [queu] writing RAW file
shifter [queu] writing RAW file
shifter [queu] compressing uploader\uploader.js with UglifyJS
shifter [queu] writing -min file
shifter [queu] compressing uploader-queue\uploader-queue.js with UglifyJS
shifter [queu] compressing uploader-flash\uploader-flash.js with UglifyJS
shifter [queu] compressing uploader-html5\uploader-html5.js with UglifyJS
shifter [queu] writing -min file
shifter [queu] writing -min file
shifter [queu] writing -min file
shifter [info] shifting for coverage
shifter [info] shifting assets for uploader
shifter [info] shifting for coverage
shifter [info] shifting assets for uploader-queue
shifter [info] shifting for coverage
shifter [info] shifting assets for uploader-flash
shifter [info] shifting for coverage
shifter [info] shifting assets for uploader-html5
shifter [queu] coverage file read, starting coverage for: uploader/uploader.js
shifter [info] yuitest providing coverage
shifter [queu] coverage file read, starting coverage for: uploader-queue/uploader-queue.js
shifter [info] yuitest providing coverage
shifter [queu] coverage file read, starting coverage for: uploader-flash/uploader-flash.js
shifter [queu] coverage file read, starting coverage for: uploader-html5/uploader-html5.js
shifter [info] yuitest providing coverage
shifter [info] yuitest providing coverage
shifter [queu] writing coverage file to uploader/uploader-coverage.js
shifter [queu] writing coverage file to uploader-queue/uploader-queue-coverage.js
shifter [queu] writing coverage file to uploader-flash/uploader-flash-coverage.js
shifter [queu] writing coverage file to uploader-html5/uploader-html5-coverage.js
shifter [info] done racing, the gears are toast
shifter [info] finished in 0.749 seconds, pretty fast huh?

**Comment by davglass** [comment]
This fix is in `yogi@0.0.60`
