### ISSUE TITLE
yogi cdn request

### ISSUE THREAD

**Issue by apipkin** [yui/yogi#4]
No matter what I commit or push to origin:master, `yogi cdn request` tells me "git root is dirty, please commit first" when in the src/ directory.

There are untracked files in the directory, but these should not be causing this issue.

**Comment by davglass** [comment]
Untracked files is not a clean git root.

**Comment by davglass** [comment]
You can install these changes with: `sudo npm -g install https://github.com/yui/yogi/archive/master.tar.gz`
