### ISSUE TITLE
annoyances upgrading to yogi 0.0.61

### ISSUE THREAD

**Issue by jafl** [yui/yogi#40]
Unfortunately, I don't remember which version I upgraded from.  The issue was that I had to manually delete three directories before the install would complete successfully.  Here are the error logs that told me about the directories:

---

npm ERR! EEXIST, mkdir '/usr/local/lib/node_modules/yogi/node_modules/combohandler/node_modules/express/node_modules/mkdirp/test'
File exists: /usr/local/lib/node_modules/yogi/node_modules/combohandler/node_modules/express/node_modules/mkdirp/test
Move it away, and try again. 

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "yogi"
npm ERR! cwd /Users/jolindal
npm ERR! node -v v0.8.8
npm ERR! npm -v 1.1.59
npm ERR! path /usr/local/lib/node_modules/yogi/node_modules/combohandler/node_modules/express/node_modules/mkdirp/test
npm ERR! fstream_path /usr/local/lib/node_modules/yogi/node_modules/combohandler/node_modules/express/node_modules/mkdirp/test/umask_sync.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/yogi/node_modules/yuidocjs/tests/out/files/input_charts_CartesianSeries.js.html'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

---

npm ERR! EEXIST, mkdir '/usr/local/lib/node_modules/yogi/node_modules/shifter/node_modules/gear-lib/node_modules/uglify-js/test/unit/compress/expected'
File exists: /usr/local/lib/node_modules/yogi/node_modules/shifter/node_modules/gear-lib/node_modules/uglify-js/test/unit/compress/expected
Move it away, and try again. 

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "yogi"
npm ERR! cwd /Users/jolindal
npm ERR! node -v v0.8.8
npm ERR! npm -v 1.1.59
npm ERR! path /usr/local/lib/node_modules/yogi/node_modules/shifter/node_modules/gear-lib/node_modules/uglify-js/test/unit/compress/expected
npm ERR! fstream_path /usr/local/lib/node_modules/yogi/node_modules/shifter/node_modules/gear-lib/node_modules/uglify-js/test/unit/compress/expected/var.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/yogi/node_modules/shifter/node_modules'
npm ERR! error rolling back  yogi@0.0.61 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/yogi/node_modules/shifter/node_modules']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/yogi/node_modules/shifter/node_modules' }
npm ERR! yeti@0.2.15pre postinstall: `node scripts/postinstall.js`
npm ERR! `sh "-c" "node scripts/postinstall.js"` failed with 1
npm ERR! 
npm ERR! Failed at the yeti@0.2.15pre postinstall script.
npm ERR! This is most likely a problem with the yeti package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls yeti
npm ERR! There is likely additional logging output above.

---

npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/yogi/node_modules/yuidocjs'
npm ERR! error rolling back  yogi@0.0.61 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/yogi/node_modules/yuidocjs']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/yogi/node_modules/yuidocjs' }
npm ERR! yeti@0.2.15pre postinstall: `node scripts/postinstall.js`
npm ERR! `sh "-c" "node scripts/postinstall.js"` failed with 1
npm ERR! 
npm ERR! Failed at the yeti@0.2.15pre postinstall script.
npm ERR! This is most likely a problem with the yeti package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls yeti
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "yogi"
npm ERR! cwd /Users/jolindal
npm ERR! node -v v0.8.8
npm ERR! npm -v 1.1.59
npm ERR! code ELIFECYCLE
npm ERR! EEXIST, mkdir '/usr/local/lib/node_modules/yogi/node_modules/shifter/node_modules/gear-lib/node_modules/glob/node_modules/inherits'
File exists: /usr/local/lib/node_modules/yogi/node_modules/shifter/node_modules/gear-lib/node_modules/glob/node_modules/inherits
Move it away, and try again. 

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "yogi"
npm ERR! cwd /Users/jolindal
npm ERR! node -v v0.8.8
npm ERR! npm -v 1.1.59
npm ERR! path /usr/local/lib/node_modules/yogi/node_modules/shifter/node_modules/gear-lib/node_modules/glob/node_modules/inherits
npm ERR! fstream_path /usr/local/lib/node_modules/yogi/node_modules/shifter/node_modules/gear-lib/node_modules/glob/node_modules/inherits/README.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/yogi/node_modules/combohandler/node_modules/express/node_modules/connect/node_modules/formidable/node-gently/Readme.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

**Comment by davglass** [comment]
Upgrade Node to the latest, this is an NPM error not a yogi error.
