### ISSUE TITLE
add a --local option to yogi init

### ISSUE THREAD

**Issue by Satyam** [yui/yogi#43]
It would be handy to allow `yogi init` to just create the directory structure for putting together simple tests or examples which will probably never live long (and should they ever do, they can later be moved under a git repository and their name registered).

**Comment by davglass** [comment]
Can you explain a little more, I'm not exactly sure what that means..

**Comment by Satyam** [comment]
Basically, getting yogi to build this file structure:

http://yui.github.com/yogi/gallery/index.html#getting-things-done

completely locally, without involving github or the gallery

**Comment by davglass** [comment]
Ok, but what else would you like to do after that. Several yogi commands rely on the git root to determine locations (`test`, `serve`, etc) and these will be useless.

Wouldn't it be just as easy to `git init && yogi init foo`?

**Comment by Satyam** [comment]
Are they?  I didn't know.  I thought that you could lint, build, test and do the API docs completely locally, which is the whole point of it all.  Anyway, shifter and yuidoc should run fine even if used without yogi, and shifter includes jshint.  You can't run test or test + coverage? 

And I am talking about not connecting with GitHub or Gallery, local git commands would be just as well.  I don't know what git init implies in terms of connectivity which is what I want to avoid.

**Comment by davglass** [comment]
90% of the things `yogi` helps with is done locally, but the requirement is that is needs to live inside a git repo. Yogi searched the file tree up looking for a place to "call home". Someplace above where you are that things start and can be served from.

`git init` is a local git repo. Nothing get's created remotely until you `git remote add origin blah && git push origin master`.

There is no connection at all and it's quick and fast (the reason I based all the commands on it, so it knows where it is).

You can `git init` in any folder you want all day long and then delete them when you are done. It's not going to hurt anything, but it will make things work better ;)

**Comment by Satyam** [comment]
Then forget it and thanks for the tip.  I didn't know it was local.  so far my experience had been to start with something on Github and then bring things to the local environment.  Good to know it is not always so.  Sorry for the trouble and thanks for the help.

**Comment by davglass** [comment]
No problem :)
