### ISSUE TITLE
yogi loader doesn't use specified condition trigger

### ISSUE THREAD

**Issue by eduardolundgren** [yui/yogi#48]
See the input/output below.

build.json:

``` javascript
{
    "node-ie": {
        "condition": {
           "trigger": "node",
           "ua": "ie"
        },

        "requires": [
        ]
    }
}
```

Generated code:

``` javascript
Y.mix(YUI.Env[Y.version].modules, {
    "node-ie": {
        "condition": {
            "name": "node-ie",
            "trigger": "node-ie",
            "ua": "ie"
        },
        "requires": [
        ]
    }
});
```

It should outputs:

``` javascript
Y.mix(YUI.Env[Y.version].modules, {
    "node-ie": {
        "condition": {
            "trigger": "node",
            "ua": "ie"
        },
        "requires": [
        ]
    }
});
```

**Comment by evocateur** [comment]
I believe the `name` property of the `condition` object should remain in the expected output, for historical reasons (I remember fixing a bug awhile back in one of my custom, hand-written conditions that was lacking the name property).

The `trigger` property is clearly being incorrectly modified, though.

**Comment by davglass** [comment]
I can't reproduce this, here is my test:

https://gist.github.com/4512144

Can you provide a step by step reproducible test please?

**Comment by eduardolundgren** [comment]
The issue cannot be reproduced anymore. Closing it for now.

**Comment by eduardolundgren** [comment]
Leaving it open to try to reproduce it.
