### ISSUE TITLE
Yogi 0.0.64 failure on new `yogi cdn request`

### ISSUE THREAD

**Issue by stlsmiths** [yui/yogi#49]
I created a new module https://github.com/stlsmiths/new-gallery/tree/master/src/gallery-datatable-contextmenu.

I've gotten a clean build (but tests fail, because a dependency is not on the CDN or over the wire anywhere yet ...), and when I do a `yogi cdn request --force` I get a NodeJS stack dump.

https://gist.github.com/4536300

Any ideas?

**Comment by davglass** [comment]
That's strange, that code hasn't changed in a long while and it's only gathering your git origin. I can't replicate it locally, so I'll leave this up until I can.

**Comment by stlsmiths** [comment]
Actually I think this was my bad, I had an extra `.git/` folder in a subfolder (think I did `git init` in a git subdir).  I deleted the .git/ folder, re-pushed and yogi did fine.  Sorry about the false alarm
