### ISSUE TITLE
JSlinting the tests

### ISSUE THREAD

**Issue by Satyam** [yui/yogi#54]
Have you tried to run JSLint on the tests?  There are lot of errors that come out of copying and pasting the same line over and over.  I haven't seen any really serious errors, but there were so many screen fulls of errors that I just sampled them, but then, what good is your testing if your calliper is failed. Lots of undefined variables which, if the "use strict" statement that JSLint complains about was there, they would all fail.

**Comment by davglass** [comment]
The modules tests? Sure I can add that.
