### ISSUE TITLE
Reporting from `yogi test --coverage`

### ISSUE THREAD

**Issue by ghost** [yui/yogi#61]
Is there any way to get a more detailed report from `yogi test --coverage`.  Specifically, I'm looking for exactly what lines / functions / branches are not covered rather than a percentage.

**Comment by davglass** [comment]
Use `yogi serve --istanbul` then run the coverage tests to see the
Istanbul report.

**Comment by ghost** [comment]
Thank you so much.  I've been struggling with this.
