### ISSUE TITLE
Path parameter for init

### ISSUE THREAD

**Issue by F21** [yui/yogi#62]
Is there any reason why I can do this (some app is a git project in `C:/projects/someapp`):

```
yogi create my-module --path C:/projects/someapp/app/js/src
```

But, can't do this?

```
yogi init my-module --path C:/projects/someapp/app/js/src
```

I think letting the init command take a path parameter would be immensely useful (especially in my use case) :)

**Comment by davglass** [comment]
`--path` is only valid for `create` because it's used for the Gallery.

**Comment by F21** [comment]
Could you expand on this to fit my situation (sorry, I am very new to yogi, shifter + friends, so I am not sure I am on the right track :))?

Let's say I have a project that is pretty big. The project is stored in `C:/projects/someapp`. This project is a git project, so I have `C:/projects/someapp/.git`.

My js files are stored in `C:/projects/someapp/app/js/src/my-module/js`. I would like the built JS to be in `C:/projects/someapp/app/js/build/my-module`.

Currently, yogi forces me to init my modules in `C:/projects/someapp/src/my-module`, which is less than ideal.

What's the best way to deal with this if I would still like to have the benefits of yogi?

**Comment by davglass** [comment]
I'll try to look into it tomorrow.
