### ISSUE TITLE
YUIDocs issue

### ISSUE THREAD

**Issue by asotog** [yui/yogi#66]
Hey team,
First at all, great tool, its awesome, was trying to access the yuidocs page with yogi serve but it throws this message in the browser "Item Not Found in internal meta-data", is it a common issue where im missing something ?
Thanks,

**Comment by davglass** [comment]
Can I get a repro case?

**Comment by asotog** [comment]
Basically was creating a new widget, doing the following steps:
- create the new widget module with: yogi create --init MODULE_NAME --type=widget
- then create a  simple class like  https://github.com/asotog88/yui3-gallery/blob/master/src/gallery-facebook-widget/js/gallery-facebook-widget.js
- then i added these comments http://jsfiddle.net/asotog88/ywM2u/ into the same class
- after yogi build and yui serve i got "Item Not Found in internal meta-data" when going into api documentation on http://127.0.0.1:5000/
- then i tried to generate the docs directly with yuidoc command and the api pages are generated with the respective comments that i put in the file

Thanks

**Comment by asotog** [comment]
Sorry forgot to mention the versions im using: yogi@0.0.75 on node@0.8.1
Thanks,

**Comment by davglass** [comment]
Might want to actually put the proper class name in:

```
* @class MyClass
* @constructor
```

**Comment by asotog** [comment]
Well i already tried with the same class name i have this http://dl.dropbox.com/u/31991620/gallery-facebook-widget.zip

**Comment by davglass** [comment]
You don't have a `@module` tag either:

```
@class FacebookWidget
@module gallery-facebook-widget
```

**Comment by asotog** [comment]
Thanks a lot man, yogi is  a great tool
