### ISSUE TITLE
yogi create ERROR

### ISSUE THREAD

**Issue by gurumvg** [yui/yogi#70]
I'm trying to create a new gallery module using yogi, but it throws below error. Appreciate any help. I'm running yogi on windows.

D:\WORK\gallery>yogi create testmodule --init

yogi [info]  using yogi@0.1.6 on node@0.10.3
yogi [bail] Unable to find parent git root, is this in a git repo?

**Comment by davglass** [comment]
Run `git init`, yogi requires a git repo.

**Comment by gurumvg** [comment]
Thanks Dav for the quick reply. It worked!
