### ISSUE TITLE
Integrate yogi with back-end

### ISSUE THREAD

**Issue by gurumvg** [yui/yogi#71]
I want to create a gallery module example which runs with a back-end code. For ex, In my gallery module example when user clicks a link, it request data from the back-end server and downloads the data as a file. I need to put the download logic at server to completely showcase my module example. Can I integrate yogi with a back-end language like Java [along with nodejs].

Thanks in advance!

**Comment by davglass** [comment]
You can integrate it with anything you want, but yogi won't do it for you. If you intend on giving this example back for the community then the backend needs to be mocked with a simple JSON request.

**Comment by gurumvg** [comment]
I'm talking abt a case where back-end is sending a byte stream instead of just json string response. How does yogi comes to rescue in this situation ?

**Comment by davglass** [comment]
That is not yogi's job, yogi is a "Developer Tool" and should only be used as such.
