### ISSUE TITLE
yogi istanbul coverage issue

### ISSUE THREAD

**Issue by gurumvg** [yui/yogi#72]
Trying to generate code coverage of my module using yogi istanbul, but I get below error. However I can see the test stats in the browser but couldn't see coverage report or can't run grover from the module landing page.  

C:\workspace\mygallery\src\gallery-mymodule>yogi build

yogi [info]  using yogi@0.1.5 on node@0.8.15
yogi [info]  using module: gallery-mymodule
yogi [info]  running with shifter
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
yogi [info]  build complete
yogi [ERROR] yogi detected an error, exiting code 1

Using, 'yogi serve --istanbul'  just shows up the test stats in the test console without showing up coverage report.

**Comment by gurumvg** [comment]
In addition, I get this error If I run on YUI3 module,

C:\WORK\YUI3\src\anim>yogi test --coverage --istanbul
yogi [info]  using yogi@0.0.75 on node@0.8.15
yogi [info]  using module: anim
yogi [info]  prepping grover tests
yogi [info]  adding tests route
yogi [info]  turning on coverage support in grover
yogi [info]  launching xdr server on port 5001
yogi [info]  listening on: http://127.0.0.1:5000
Starting Grover on 3 files with PhantomJS@1.9.0
  Running 15 concurrent tests at a time.

C:\Program Files\nodejs\node_modules\yogi\lib\cmds\serve.js:542
                res.tyle(path.extname(file));
                    ^
TypeError: Object #<ServerResponse> has no method 'tyle'
    at mods.parseAndServe.fs.readFile.res.charset (C:\Program Files\nodejs\node_modules\yogi\lib\cmds\serve.js:542:21)
    at mods.serveCoverage (C:\Program Files\nodejs\node_modules\yogi\lib\cmds\serve.js:475:21)
    at Object.Instrumenter.instrument (C:\Program Files\nodejs\node_modules\yogi\node_modules\istanbul\lib\instrumenter.js:415:17)
    at mods.serveCoverage (C:\Program Files\nodejs\node_modules\yogi\lib\cmds\serve.js:473:22)
    at fs.readFile (fs.js:176:14)
    at fs.close (C:\Program Files\nodejs\node_modules\yogi\node_modules\cpr\node_modules\graceful-fs\graceful-fs.js:90:5)
    at Object.oncomplete (fs.js:297:15)

FYI, I'm working on a WINDOWS machine. Thanks!

**Comment by davglass** [comment]
Can you try with the latest yogi version?

**Comment by gurumvg** [comment]
The issue was with the missing 'io' & 'json' yui dependencies when bootstrapping the Y.Test.Runner in the tests/unit/index.html file.

**Comment by davglass** [comment]
> The issue was with the missing 'io' & 'json' yui dependencies when bootstrapping the Y.Test.Runner in the tests/unit/index.html file.

Can you explain what this means?

**Comment by gurumvg** [comment]
I missed specifying 'io' & 'json' dependencies in the 'use' call which runs my unit test cases.
