### ISSUE TITLE
Unable to launch 'API Documentation' page.

### ISSUE THREAD

**Issue by gurumvg** [yui/yogi#73]
Unable to launch 'API Documentation' page. Below is the error.

C:\my-gallery\src\my-module>yogi serve
yogi [info]  using yogi@0.1.5 on node@0.10.3
yogi [info]  using module: my-module
yogi [info]  adding tests route
yogi [info]  this is yui, using global path for all docs
yogi [info]  launching yuidoc --server 5001 --config C:\my-gallery\src\common\api\yuidoc.json
yogi [info]  this is yui, using global path for all docs
yogi [info]  launching selleck --server 5003 --project C:\my-gallery\src\common\docs\
yogi [info]  launching xdr server on port 5004
yogi [info]  listening on: http://127.0.0.1:5000

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: connect ECONNREFUSED
    at errnoException (net.js:878:11)
    at Object.afterConnect [as oncomplete](net.js:869:19)

Any help is appreciated!

**Comment by davglass** [comment]
I can't replicate this locally, can you use `yogi serve --debug` and report it's output please?

**Comment by gurumvg** [comment]
I get pretty much same error message when i use --debug.

**Comment by gurumvg** [comment]
In addition, I get below trivial error message from selleck in my console. Anything to do with this ?

yogi [ERROR] selleck: Error: OK, read
yogi [ERROR] selleck: Error: OK, read
yogi [ERROR] selleck: Error: OK, read
yogi [ERROR] selleck: Error: EBADF, read
yogi [ERROR] selleck: Error: OK, read
yogi [ERROR] selleck: Error: OK, read
yogi [ERROR] selleck: Error: OK, read
yogi [ERROR] selleck: Error: OK, read
yogi [ERROR] selleck: Error: EBADF, read
yogi [ERROR] selleck: Error: EBADF, read
yogi [ERROR] selleck: Error: OK, read
yogi [ERROR] selleck: Error: OK, read
yogi [ERROR] selleck: Error: OK, read
yogi [ERROR] selleck: Error: EBADF, read
yogi [ERROR] selleck: Error: OK, read
yogi [ERROR] selleck: Error: OK, read
yogi [ERROR] selleck: Error: OK, read

**Comment by davglass** [comment]
Yes, that's helpful.. Now I have to actually reproduce this. For now, can you install Node 0.8.22 and try it. That version of Node is much more stable.

**Comment by gurumvg** [comment]
Any update on this Dave ? For some reasons, I can't switch back to Node 0.8.22.

**Comment by davglass** [comment]
For some reason `yogi` thinks that your gallery module is the yui module:

```
yogi [info] this is yui, using global path for all docs
```

Where is this code so that I can clone it to test??

**Comment by caridy** [comment]
old ticket, closing!
