### ISSUE TITLE
yogi serve --watch not working with new modules

### ISSUE THREAD

**Issue by ignaciocavina** [yui/yogi#75]
`yogi serve --watch` seems not to be working, at least not with newly created modules using yogi init... thou it does worked fine with, for example, yui3/calendar...  

After init'ing a new module and running `yogi serve --watch` I'm getting this:

```
yogi [info]  shifter watching for changes

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:975:11)
    at Process.ChildProcess._handle.onexit (child_process.js:766:34)
```

**Comment by caridy** [comment]
just restart yogi serve when creating new modules!
