### ISSUE TITLE
where to place my custom node.js servlet code ?

### ISSUE THREAD

**Issue by gurumvg** [yui/yogi#78]
I'm working on a module which is sort of ajax download. I need to put the back-end (servlet) download node.js  (file creation) code as part of yogi / yui3 codebase, so that  I can showcase my module functionality as an example, so that I can make a `Y.io` call to that servlet ?
Appreciate any help!

**Comment by ekashida** [comment]
Hey @gurumvg, you can use yogi to stub out HTTP requests. Here's an [example](https://github.com/yui/yui3/blob/master/src/get/tests/unit/assets/get-test.js). You can also check out the [echoecho](https://github.com/davglass/echoecho) documentation for more details on the types of requests you can make.

**Comment by gurumvg** [comment]
:+1:
