### ISSUE TITLE
yogi on windows errors out

### ISSUE THREAD

**Issue by mattparker** [yui/yogi#8]
I'm getting an error:

$ yogi build -- load
yogi [info] using yogi@0.0.44 on node@0.8.11
yogi [info] using module: gallery-color-palette
yogi [info] running with shifter
yogi [info] build complete
yogi [ERROR] yogi detected an error, exiting code 1

$

I'll try it again with yogi init - the one it's working on was set up manually...

**Comment by benjamind** [comment]
I can confirm this bug on Windows, even when setting up with yogi init.

**Comment by foxxtrot** [comment]
Please provide the output of a Yogi command running with '--loglevel=debug'

**Comment by davglass** [comment]
FYI: `yogi --debug` also works

## 

Dav Glass
davglass@gmail.com
blog.davglass.com
- Windows: n. - The most successful computer virus, ever. +
- A computer without a Microsoft operating system is like a dog
  without bricks tied to its head +
- A Microsoft Certified Systems Engineer is to computing what a
  McDonalds Certified Food Specialist is to fine cuisine  +

**Comment by mattparker** [comment]
$ yogi build -- loud --loglevel=debug 
gives the same as above

$ yogi build --loglevel=debug
yogi [debug] initializing config
yogi [debug] Locating .yogi.json file
yogi [debug] Loading config file from: C:\Users\Matt.yogi.json
yogi [info]  using yogi@0.0.44 on node@0.8.11
yogi [debug] starting up yogi
yogi [debug] I'm smarter than the av-er-age bear!
yogi [debug] finding module from n:\wamp\yui3contrib\gallery-color-palette
yogi [debug] looking for build.json file
yogi [debug] found something here: n:\wamp\yui3contrib\gallery-color-palette\
yogi [info]  using module: gallery-color-palette
yogi [info]  running with shifter
yogi [debug] shifter finished, clean up
yogi [debug] cleaning up
yogi [info]  build complete
yogi [ERROR] yogi detected an error, exiting code 1

**Comment by davglass** [comment]
That still smells like the `stderr` on Windows is populated with
garbage (likely a `\r`). I have guests tonight, but I may be able to
provide a quick patch if I have any downtime waiting on my stain to
dry ;)

**Comment by mattparker** [comment]
No, thought you were on holiday, leave it... At the most, point me in the right direction and I'll look later.

**Comment by davglass** [comment]
Under `lib/cmds/build.js` there's a section that checks the `stderr`.
That's likely getting tripped.

**Comment by benjamind** [comment]
Just submitted a pull request which I think fixes this issue. It boils down to ChildProcess under windows not allowing you to call a shell script (.cmd) as a proper Win32 application. You need to wrap it in a shell first. The win-spawn package does this and keeps the changes in yogi simple enough that it should be easy to back out later when / if this gets fixed in node core.

**Comment by mattparker** [comment]
Thanks for the fix, I'd got as far as spawn but then got called away...

**Comment by davglass** [comment]
Pushed in `yogi@0.0.45`
