### ISSUE TITLE
yogi init should warn about module name conflicts

### ISSUE THREAD

**Issue by solmsted** [yui/yogi#81]
I wanted to do a quick test for something, so I did `yogi init test`.  Then in the new test directory, `yogi info` reported the following:

```
yogi [info]  using yogi@0.1.9 on node@0.10.5
yogi [info]  using module: test
yogi [info]  showing info for test
yogi [warn]  this is a yogi only module and will be hidden from the site

       clone this request:
           git clone git://github.com/eduardolundgren/alloy.git
           cd alloy/src/gallery-test

   next cdn deployment window is Wed Jun 05 2013 16:00:00 GMT-0400 (EDT)

yogi [warn]  yogi could not find any remote test data, has a CDN request been processed yet?
```

Since I am not eduardolundgren, I found this strange.  I assume someone else did a `yogi create` with a module named test.

I feel like Yogi should throw up a big scary warning and possibly an extra [y/n] confirmation when generating a module with a duplicate name.

**Comment by caridy** [comment]
noop
