### ISSUE TITLE
Provide way to use a custom yuidoc.json

### ISSUE THREAD

**Issue by ItsAsbreuk** [yui/yogi#87]
I found out the only way to customize yuidoc.json is by changing /usr/local/lib/node_modules/yogi/configs/yuidoc/yuidoc.json.

However, this json-file gets replaced every time you upgrade yogi.
So it would be better if we have a way to use a custom yuidoc.json file

I think many would like to add options.external.data = "http://yuilibrary.com/yui/docs/api/data.json" 

Marco.

**Comment by caridy** [comment]
old ticket, closing!
