### ISSUE TITLE
Property-error in configs/selleck/project.json

### ISSUE THREAD

**Issue by ItsAsbreuk** [yui/yogi#88]
I think

"yuiSeedUrl": "/yui/yui-min.js"
should be
"yuiSeedUrl": "/build/yui/yui-min.js"

Kind regards,
Marco

**Comment by caridy** [comment]
starting on 3.5.0, `build` is not longer required, both urls will work:

http://yui.yahooapis.com/3.5.0/build/yui/yui.js
http://yui.yahooapis.com/3.5.0/yui/yui.js

not so sure how does that works in the context of yogi though.

**Comment by ItsAsbreuk** [comment]
Hi Caridy,

Well, then this modification didn't get its way down to yogi (or selleck?)

1) goto workdirectory "src" --> that is the parentdir of the modules
2) run "yogi serve --port 5000"
3) goto localhost:5000/docs/  (by clicking 'Examples and Landing Page')

--> you get a http 404-error on http://localhost:5000/yui/yui-min.js

However making the suggested changes to project.json will load http://localhost:5000/build/yui/yui-min.js which returns fine.

NOTE: if you start yogi inside one module, it will go to http://localhost:5000/docs/your-module/ instead of http://localhost:5000/docs/. The strange thing is, that http://localhost:5000/docs/your-module/ will load http://localhost:5000/build/yui/yui-min.js by default instead of http://localhost:5000/yui/yui-min.js, so here you see no 404-error.

The 404 only occurs on page localhost:5000/docs/

Marco.

**Comment by caridy** [comment]
old ticket, closing!
