### ISSUE TITLE
yogi login fails 

### ISSUE THREAD

**Issue by Satyam** [yui/yogi#9]
```
satyam@ubuntu:~/git$ yogi login
yogi [info]  using yogi@0.0.44 on node@0.6.10

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<Object> has no method 'resume'
    at new Interface (readline.js:58:9)
    at Object.createInterface (readline.js:38:10)
    at Object.prompt (/usr/lib/node_modules/yogi/lib/util.js:184:27)
    at Object.process (/usr/lib/node_modules/yogi/lib/cmds/login.js:34:22)
    at Object.init (/usr/lib/node_modules/yogi/lib/cmds/login.js:17:14)
    at Object.<anonymous> (/usr/lib/node_modules/yogi/bin/yogi.js:31:9)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
```

Did: `sudo npm -g update`, just in case, but it didn't change anything.  Also tried `sudo yogi login` and it also fails.

**Comment by davglass** [comment]
Please try using the latest stable version of node. Your node version is very old.

**Comment by Satyam** [comment]
I don't understand where it is picking that version.  I have automatic updates.  This is from the same machine:

```
satyam@ubuntu:~$ which nodejs
/usr/bin/nodejs
satyam@ubuntu:~$ nodejs --version
v0.8.14
```

How come yogi reports such an old version?  Where could it be pulling it from?  I'll try to find out, do you have any idea what might be happening?  Thanks

**Comment by davglass** [comment]
`/usr/bin/env node` should report the system installed version.

**Comment by Satyam** [comment]
It seems I have two versions then:

```
satyam@ubuntu:~$ /usr/bin/env node --version
v0.6.10
```

I've always been a Windows person, I'm just starting with Linux.  How can I locate and delete that old version?

**Comment by Satyam** [comment]
perhaps the safest is to use the package manager to uninstall whatever it has installed (which is the one being updated) and then wipe out whatever other version I might find?  Anyway, where would I look for other versions?

**Comment by Satyam** [comment]
Never mind, I found it.  Thanks.

**Comment by Satyam** [comment]
BTW: it works now.
